- alias: Reset office PIR state
  hide_entity: true
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.office_motion
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  action:
    service: mqtt.publish
    data:
      topic: rf_bridge/tele/RESULT
      payload: F60A9Eoff

- alias: Office lights on
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.office

- alias: Office lights off
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'off'
    for:
      minutes: 20
  action:
    service: light.turn_off
    entity_id: light.office
