
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: butterworths.duckdns.org:8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/fullchain.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
zone: !include zones.yaml
binary_sensor: !include sensors.yaml

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip

  
